### ISSUE TITLE
SymbolTree : graphic bug if Gtk.TreeView size exceeds current container size

### ISSUE THREAD

**Issue by inizan-yannick** [inizan-yannick/vala-editor#4]
![capture d ecran_2016-02-10_03-59-15](https://cloud.githubusercontent.com/assets/3141337/12937623/b82e2aec-cfaa-11e5-9229-b02b12d01529.png) ![capture d ecran_2016-02-10_03-59-30](https://cloud.githubusercontent.com/assets/3141337/12937624/b832cae8-cfaa-11e5-9084-9408e3f0c5c8.png)

**Comment by powerwaremediacore** [comment]
Have yoi tryed gtk inspector and check if your widget expand according with your parent.

I suppose you are using a Gtk.Popover? Then should your child be a Gtk.Grid expanded to your tree? Sorry I don't see all your code.

**Comment by inizan-yannick** [comment]
The problem cames from ScrolledWindow inside Paned. Now I use Box.

**Comment by inizan-yannick** [comment]
ok. same problem with Box. maybe an error with Gtk version

**Comment by inizan-yannick** [comment]
If someone have Gtk < 3.19, please try last commit

**Comment by inizan-yannick** [comment]
no effect with Gtk 3.18.7, seems an error during update of TreeStore
