### ISSUE TITLE
Error on configure with vala 0.30

### ISSUE THREAD

**Issue by bitseater** [inizan-yannick/vala-editor#8]
When I try : ./configure --with-vala=0.30 , it stop in the next error:

./configure: line 12641: syntax error near unexpected token `0.9.0'
./configure: line 12641: `GOBJECT_INTROSPECTION_CHECK(0.9.0)'

**Comment by SkyzohKey** [comment]
Works well for me :/

**Comment by inizan-yannick** [comment]
fixed in last commit.
